In [ ]:
pip install matplotlib


In [ ]:
# Board in 19x19 grid representation
import numpy as np

board_str = [
    "XXXXXXXXXXX0000000",
    "XXXXXXXXXXX0000000",
    "XXXXXXXXXXX0000000",
    "XXXXXXXXX000000000",
    "XXXXXX000000000000",
    "XXXXX0000000000000",
    "XXXXX0000000000000",
    "XXXXX0000000000000",
    "XXX000000000000000",
    "XXX00000000000000X",
    "XXX000000000000XXX",
    "X00000000000000XXX",
    "0000000000000XXXXX",
    "000000000000XXXXXX",
    "000000000XXXXXXXXX",
    "000000000XXXXXXXXX",
    "000000000XXXXXXXXX",
    "00000000XXXXXXXXXX",
    "00000000XXXXXXXXXX"
]

# Pad the board_str lines to ensure they have 19 columns
board_str = [line.ljust(BOARD_COLS, '0') for line in board_str]

# Convert to a NumPy array (0 = free, -1 = blocked)
board = np.array([[0 if cell == '0' else -1 for cell in row] for row in board_str])


print(board)

BOARD_COLS = 19;
BOARD_ROWS = 19;

# Define puzzle pieces using numpy arrays
pieces = [
    np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    ]),  # Piece 1

    np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    ]),  # Piece 2

    np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    ]),  # Piece 3

    np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    ])  # Piece 4
]


[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0  0]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0  0]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0  0]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0]
 [-1 -1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [-1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [-1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [-1 -1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [-1 -1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [-1 -1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0]
 [-1 -1 -1  0  0  0  0  0  0  0  0  0  0  0  0 -1 -1 -1  0]
 [-1  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1 -1 -1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 -1 -1 -1 -1 -1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 -1 -1 -1 -1 -1 -1  0]
 [ 0  0  0  0  0  0  0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1  0]
 [ 0  0  0  0  0  0  0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1  0]
 [ 0  0  0  0  0  0  0  0  0 -1 -1 -1 -1

In [ ]:
import numpy as np

def rotate_piece(piece, rotation):
    """Rotate the piece 90 degrees 'rotation' times."""
    return np.rot90(piece, rotation)

def flip_piece(piece):
    """Flip the piece horizontally."""
    return np.fliplr(piece)

def can_place(board, piece, x, y):
    """Check if the piece can be placed at (x, y) on the board."""
    rows, cols = piece.shape
    if x + rows > BOARD_ROWS or y + cols > BOARD_COLS:
        return False  # Out of bounds

    for i in range(rows):
        for j in range(cols):
            if piece[i, j] != 0 and board[x + i, y + j] != 0:
                return False  # Overlap with an existing piece or blocked space
    return True

def place_piece(board, piece, x, y, piece_id):
    """Place the piece on the board."""
    new_board = board.copy()
    rows, cols = piece.shape
    for i in range(rows):
        for j in range(cols):
            if piece[i, j] != 0:
                new_board[x + i, y + j] = piece_id
    return new_board

def solve(board, pieces, index=0):
    """Recursive backtracking solver with debugging."""
    if index == len(pieces):
        return board  # All pieces placed

    piece_id = index + 1
    piece = pieces[index]

    for rotation in range(4):  # Try 4 rotations
        rotated_piece = rotate_piece(piece, rotation)
        flipped_piece = flip_piece(rotated_piece)

        for p in [rotated_piece, flipped_piece]:  # Try original and flipped
            for x in range(BOARD_ROWS):
                for y in range(BOARD_COLS):
                    if can_place(board, p, x, y):
                        print(f"Placing piece {piece_id} at ({x}, {y})")
                        new_board = place_piece(board, p, x, y, piece_id)
                        result = solve(new_board, pieces, index + 1)
                        if result is not None:
                            return result  # Solution found
                        print(f"Backtracking piece {piece_id} from ({x}, {y})")
    print(f"No valid placement found for piece {piece_id}")
    return None  # No valid placement found

# Solve the puzzle
solved_board = solve(board, pieces)
print("Final Board:")
print(solved_board if solved_board is not None else "No solution found")


Placing piece 1 at (2, 7)
No valid placement found for piece 2
Backtracking piece 1 from (2, 7)
No valid placement found for piece 1
Final Board:
No solution found


In [1]:
#nope !!! INGORE !!!!!!!!
import numpy as np
import matplotlib.pyplot as plt


def rotate_piece(piece, rotation):
    """Rotate the piece 90 degrees 'rotation' times."""
    return np.rot90(piece, rotation)

def flip_piece(piece):
    """Flip the piece horizontally."""
    return np.fliplr(piece)

def can_place(board, piece, x, y):
    """Check if the piece can be placed at (x, y) on the board."""
    rows, cols = piece.shape
    if x + rows > BOARD_ROWS or y + cols > BOARD_COLS:
        return False  # Out of bounds

    # Check if it overlaps with a blocked area or another piece
    for i in range(rows):
        for j in range(cols):
            if piece[i, j] != 0 and board[x + i, y + j] != 0:  # Changed this condition
                return False
    return True


    # Check if it overlaps with a blocked area or another piece
    for i in range(rows):
        for j in range(cols):
            if piece[i, j] == 1 and board[x + i, y + j] != 0:
                return False
    return True

def place_piece(board, piece, x, y, piece_id):
    """Place the piece on the board (modify board)."""
    rows, cols = piece.shape
    for i in range(rows):
        for j in range(cols):
            if piece[i, j] == 1:
                board[x + i, y + j] = piece_id

def remove_piece(board, piece, x, y):
    """Remove the piece from the board (backtracking)."""
    rows, cols = piece.shape
    for i in range(rows):
        for j in range(cols):
            if piece[i, j] == 1:
                board[x + i, y + j] = 0

def solve(board, piece_index):
    """Backtracking solver for the puzzle."""
    if piece_index >= len(pieces):
        return True  # All pieces placed successfully

    piece = pieces[piece_index]
    for rotation in range(4):  # Try 4 rotations
        rotated_piece = rotate_piece(piece, rotation)
        flipped_piece = flip_piece(rotated_piece)

        for p in [rotated_piece, flipped_piece]:  # Try original and flipped
            for x in range(BOARD_ROWS):
                for y in range(BOARD_COLS):
                    if can_place(board, p, x, y):
                        place_piece(board, p, x, y, piece_index + 1)
                        if solve(board, piece_index + 1):
                            return True  # Solution found
                        remove_piece(board, p, x, y)  # Backtrack

    return False  # No solution found

# Solve the puzzle
if solve(board, 0):
    print("Solution found:")
else:
    print("No solution possible.")

# Visualization function
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

def draw_board(board):
    """Visualize the board using Matplotlib with different colors for different pieces."""

    # Define a custom color map for different pieces
    cmap = mcolors.ListedColormap([
        'white',  # 0 - Empty space
        'red',    # 1 - Piece 1
        'blue',   # 2 - Piece 2
        'green',  # 3 - Piece 3
        'orange', # 4 - Piece 4
        'gray'    # -1 - Blocked area
    ])

    # Define boundaries for colors
    bounds = [-1.5, -0.5, 0.5, 1.5, 2.5, 3.5, 4.5]
    norm = mcolors.BoundaryNorm(bounds, cmap.N)

    # Plot the board
    plt.figure(figsize=(10, 10))
    plt.imshow(board, cmap=cmap, norm=norm, origin="upper")

    # Draw grid lines
    for i in range(BOARD_ROWS + 1):
        plt.axhline(i - 0.5, color='black', linewidth=0.5)
    for j in range(BOARD_COLS + 1):
        plt.axvline(j - 0.5, color='black', linewidth=0.5)

    plt.xticks(range(BOARD_COLS))
    plt.yticks(range(BOARD_ROWS))
    plt.grid(False)  # Turn off default Matplotlib grid to avoid overlap
    plt.show()

# Call the function to visualize the board
draw_board(board)

print(np.unique(board))

NameError: name 'board' is not defined